-- lua/bootstrap.lua
--
-- Post-load initialization.
-- Colorscheme and primary UI setup are handled by plugin config callbacks.
-- This file is kept for any post-load initialization that does not
-- belong to a specific plugin.
